---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebiri
# description will be included in the image's metadata
description: The silverblue-main image from Universal Blue with niri included. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - niri
        - breeze-cursor-theme
        - breeze-gtk
        - breeze-icon-theme
        - firefox
        - firewall-config
        - lxqt-about
        - lxqt-archiver
        - lxqt-config
        - lxqt-globalkeys
        - lxqt-notificationd
        - lxqt-openssh-askpass
        - lxqt-panel
        - lxqt-policykit
        - lxqt-powermanagement
        - lxqt-qtplugin
        - lxqt-runner
        - lxqt-session
        - lxqt-themes
        - lxqt-themes-fedora
        - lxqt-wayland-session-default-compositor-miriway
        - network-manager-applet
        - niri
        - nm-connection-editor
        - notification-daemon
        - obconf
        - perl-File-MimeInfo
        - upower
        - xdg-user-dirs

  - type: chezmoi
    repository: ""
    disable-init: true
    disable-update: true

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
        - Noto

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
