---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebiri
# description will be included in the image's metadata
description: The bluefin image from Universal Blue with niri included. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
        files:
          - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
          - https://packages.microsoft.com/yumrepos/edge/config.repo
        cleanup: true
    install:
      packages:
        - niri
        - fuzzel
        - waybar
        - xdg-desktop-portal
        - mako
        - polkit-kde
        - swww

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
